"""empty message

Revision ID: 8e3b99dad050
Revises: 
Create Date: 2022-09-15 00:32:48.866695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e3b99dad050'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('especie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('especie', sa.String(length=30), nullable=False),
    sa.Column('habilidades', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('especie'),
    sa.UniqueConstraint('especie')
    )
    op.create_table('pokemones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('ataque', sa.String(length=30), nullable=False),
    sa.Column('defensa', sa.String(length=30), nullable=False),
    sa.Column('evoluciones', sa.String(length=30), nullable=False),
    sa.Column('imagene', sa.String(length=30), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('email')
    )
    op.create_table('fav__especie',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('Especie_especie', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['Especie_especie'], ['especie.especie'], ),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fav__pokemones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pokemones_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['email'], ['user.email'], ),
    sa.ForeignKeyConstraint(['pokemones_id'], ['pokemones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fav__pokemones')
    op.drop_table('fav__especie')
    op.drop_table('user')
    op.drop_table('pokemones')
    op.drop_table('especie')
    # ### end Alembic commands ###
